### ISSUE TITLE
unknown error while processing the markdown tokens.md

### ISSUE THREAD

**Issue by JamieShip** [solana-foundation/developer-content#224]
### Problem
https://solana.com/zh/docs/core/tokens 

unknown error while processing the markdown content.

### Proposed Solution
<img width="681" alt="image" src="https://github.com/solana-foundation/developer-content/assets/109888946/cf12c3eb-3a8f-4ef5-a5a7-ba6612fe4981">

**Comment by nickfrosty** [comment]
I will look into this. The odd thing to me is that the content of this document does not appear to have translations to this language and yet it is breaking.....

**Comment by nickfrosty** [comment]
@JamieShip thanks for flagging this! I just push an update to solana.com that fixes this (and should prevent it in the future)

In a nutshell, our content translation platform Crowdin was altering the content of the markdown files to a point where our MDX parser would fail to parse them correctly due to some badly formatted content that Crowdin would return to us. 

I improved that parser error handling, pre-parsing logic, and even added a more helpful error (with a direct link to create an issue) should something like this happen again :)
