### ISSUE TITLE
Broken translations causing build failure

### ISSUE THREAD

**Issue by jacobcreech** [solana-foundation/developer-content#225]
### Problem

```
 "i18n/ru/content/guides/getstarted/local-rust-hello-world.md" of type "GuideRecord" has the following incompatible fields:
       • date: "" 
```

### Proposed Solution

Have some way to avoid this error in the future. Maybe default date as a stopgap? Accepting these via crowdin should have some kind of verifying build.

**Comment by nickfrosty** [comment]
It looks like the translator removed the date for some reason....
Maybe we should update all dates to a more numeric format so that it is more clear to all language speakers that are performing translations

I just manually fixed this one problem document and will think through a more comprehensive testing before translations would go live. This also could be a misconfigured crowdin permissions setting for the translator
