### ISSUE TITLE
confusion about SPL tokens

### ISSUE THREAD

**Issue by Daudxu** [solana-foundation/developer-content#242]
### Problem
How to code to transfer SPL tokens to another account. I see that the code you wrote is quite confusing. Your system is too difficult compared to EVM, and the documentation is confusing. @ solana/wallet adapter read, @ solana/spl token, @ solana/web3. js

### Proposed Solution

How to code to transfer SPL tokens to another account. I see that the code you wrote is quite confusing. Your system is too difficult compared to EVM, and the documentation is confusing. @ solana/wallet adapter read, @ solana/spl token, @ solana/web3. js

**Comment by Dutch-TS-Dev** [comment]
I have been trying to days to make a simple SPL transaction. what should be a one-liner is absolutely brutal. None of the online tutorials work, the official documentation is wrong (gives a "from" argument instead of a "to" wallet argument. Can someone please reply? No idea why it's so insanely hard to do something so simple

**Comment by heyAyushh** [comment]
@Dutch-TS-Dev would love if you can point me to official documentation you mentioned,
till then you can try https://solana.com/developers/cookbook/transactions/send-tokens
